#ifndef PATIKA_VERSION_H
#define PATIKA_VERSION_H

#define PATIKA_VERSION_MAJOR 0
#define PATIKA_VERSION_MINOR 3
#define PATIKA_VERSION_PATCH 0

#define PATIKA_VERSION_STRING "0.3.0"

#endif /* PATIKA_VERSION_H */
